### ISSUE TITLE
Feature Request: Showing the news as org mode links

### ISSUE THREAD

**Issue by sjbalaji** [clarete/hackernews.el#13]
Hey it would be really nice if you can make it show the news articles as org mode links. One of the advantage would be to open the news article using browse-url-text-emacs or browse-url-w3. One need not leave the emacs to read the news article!! 

Waiting to hear from you about the same !!
- Balaji

**Comment by shassard** [comment]
This was fixed in commit 00b329fd9b4e8f02733fd5a0ce3e14b7a520a514.

**Comment by basil-conto** [comment]
This seems to have been fixed; closing until further notice.
