### ISSUE TITLE
"Bad news, bro: stringp"

### ISSUE THREAD

**Issue by tbronchain** [clarete/hackernews.el#15]
Hey,
It seems like it's not working, I keep getting the error "Bad news, bro: stringp" while displaying the news "[132]".
Hope you're still have time to maintain the project, otherwise I'll try to have a look when I get some spare time.
Cheers!

**Comment by bashrc** [comment]
It might be because the api url returns lines with empty strings and null urls, like this.

{"title":"","url":null,"id":8938223,"commentCount":55,"points":387,"postedAgo":"14 hours ago","postedBy":"sinak"},

**Comment by shassard** [comment]
I've submitted a pull request which changes the backend data source to Hackernews' official REST API over at Firebase. It resolves this issue.

**Comment by clarete** [comment]
Yup, I just applied that. I'll close this bug but please, feel free to open it again if you guys see this error. Also, I'll change this weird message to something better! Thanks a lot!

**Comment by tbronchain** [comment]
cool, thanks guys!
