### ISSUE TITLE
Add AUTHORS file

### ISSUE THREAD

**Issue by basil-conto** [clarete/hackernews.el#50]
The significant recent contribution of @matthew-piziak in #48 for tracking visited links made we wonder whether we should maintain a list of authors along with a brief description of their contributions, as per [`(maintain) Recording Contributors`](https://www.gnu.org/prep/maintain/html_node/Recording-Contributors.html).

Drawing heavily from [`etc/AUTHORS`](http://git.savannah.gnu.org/cgit/emacs.git/tree/etc/AUTHORS) in GNU Emacs, we could write something like the following:

    Several people have contributed code and documentation to the
    hackernews.el Hacker News client for GNU Emacs.  To show our
    appreciation for their public spirit, we list here in alphabetical
    order a condensed list of their contributions.

    ...

    Matthew Piziak: added support for tracking visited links to
      hackernews.el

    ...

WDYT? @clarete?

**Comment by matthew-piziak** [comment]
Thanks for the experience! I'm sure it would have been easier for you to just bang it out yourself, but your comments taught me so much about Emacs Lisp and package development, and I really appreciate it. :)

**Comment by basil-conto** [comment]
@matthew-piziak Thank you once again for working on this feature. I'm glad you enjoyed contributing to this project and hope you stick around for more. :)

> I'm sure it would have been easier for you to just bang it out yourself

Not necessarily; it's easier to stand on others' shoulders. :)

**Comment by clarete** [comment]
I think this is a great way to acknowledge people's contributions and also might make it easy to know who to talk to about a certain feature if you're interested in hacking on it or something like that! Definitely a +1 here!
