### ISSUE TITLE
Tries to open new instance of firefox, instead of opening in a tab

### ISSUE THREAD

**Issue by fitzgen** [clarete/hackernews.el#6]
When I click or hit RET on an item, it tries to open a new instance of firefox instead of just adding a new tab.

![screen shot](https://f.cloud.github.com/assets/74571/1363653/90571a70-382f-11e3-8d55-1ee19917ae3f.png)

**Comment by clarete** [comment]
Closing this one since it seems to be a problem in the environment. Feel free to re-open it if there's more info about the case.
